# Generated by Django 5.2 on 2026-05-27 17:17

import apps.articulo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_articulo', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('resumen', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('archivo_pdf', models.FileField(upload_to=apps.articulo.models.ruta_pdf_articulo)),
                ('revista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='revista.revista')),
            ],
            options={
                'db_table': 'articulo',
                'ordering': ('-fecha_publicacion', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='ArticuloAutor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_articulo_autor', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden_autor', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_autores', to='articulo.articulo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_articulos', to='autor.autor')),
            ],
            options={
                'db_table': 'articulo_autor',
                'ordering': ('orden_autor',),
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='autores',
            field=models.ManyToManyField(related_name='articulos', through='articulo.ArticuloAutor', to='autor.autor'),
        ),
        migrations.AddConstraint(
            model_name='articuloautor',
            constraint=models.UniqueConstraint(fields=('articulo', 'autor'), name='uq_articulo_autor'),
        ),
        migrations.AddConstraint(
            model_name='articuloautor',
            constraint=models.UniqueConstraint(fields=('articulo', 'orden_autor'), name='uq_articulo_orden_autor'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['fecha_publicacion'], name='articulo_fecha_p_0c4bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['titulo'], name='articulo_titulo_e30462_idx'),
        ),
    ]
