# Generated by Django 5.2 on 2026-05-27 17:17

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_autor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
            options={
                'db_table': 'autor',
                'ordering': ('apellido', 'nombre'),
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='autor_apellid_3934c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilAutor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='authors_profile_img/')),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('afiliacion', models.CharField(blank=True, max_length=150, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='autor.autor')),
            ],
            options={
                'db_table': 'perfil_autor',
            },
        ),
    ]
