# Generated by Django 5.2 on 2026-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilautor',
            name='ciudad',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
