# Generated by Django 5.2 on 2026-05-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_perfilautor_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilautor',
            name='ciudad',
        ),
    ]
