# Generated by Django 5.2 on 2026-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_revista', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('issn', models.CharField(max_length=9, unique=True)),
                ('factor_impacto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'revista',
                'ordering': ('nombre',),
                'indexes': [models.Index(fields=['nombre'], name='revista_nombre_c33b64_idx'), models.Index(fields=['issn'], name='revista_issn_29d0b5_idx')],
            },
        ),
    ]
